[workspace]
resolver = "2"

members = [
    "async",
    "chat",
    "chat/bot",
    "chat/room",
    "collector",
    "capacitor",
    "decoder",
    "fib",
    "mem",
    "guestbook",
    "meta",
    "minimal",
    "multiping",
    "panicker",
    "ping",
    "sum",
    "vec",
    "wait",
]

[profile.release]
lto = true
opt-level = 's'
