[package]
name = "demo-payload"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2018"
license = "GPL-3.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
gstd = { path = "../../gstd", features = ["debug"]}
serde = { version = "1.0.100", default-features = false, features = ["derive"] }
serde_json = { git = "https://github.com/breathx/json", default-features = false, features = ["alloc"] }
